version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_USER }}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  odoo:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    container_name: ${ODOO_CONTAINER_NAME}
    volumes:
      - odoo_data:/var/lib/odoo

volumes:
  db_data:
  odoo_data:
