name: Build and Push Odoo image

# Controls when the workflow will run
on:
  push:
    branches:
      - dev  # or the branch you want to trigger the workflow on

# Define jobs for the workflow
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependenies
        run: |
          pip install requirements.txt

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      

      # Optionally, install Node.js dependencies if needed
      # - name: Install Node.js dependencies
      #   run: npm install

      - name: Build Odoo
        run: python setup.py build

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:dev .

      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:dev

      # Define caching for dependencies
    # env:
    #   PIP_CACHE_DIR: ${{ github.workspace }}/.pip_cache
    #   NPM_CACHE_DIR: ${{ github.workspace }}/.npm_cache
    # cache:
    #   paths:
    #     - .pip_cache
    #     - .npm_cache
    # Define steps to execute
